# Generated by Django 6.0 on 2025-12-26 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blog_image_alter_blog_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Оценка (1–10)')),
                ('design', models.CharField(choices=[('Отлично', 'Отлично'), ('Хорошо', 'Хорошо'), ('Нормально', 'Нормально'), ('Плохо', 'Плохо')], max_length=20, verbose_name='Оформление сайта')),
                ('features', models.CharField(blank=True, max_length=200, verbose_name='Что понравилось')),
                ('topic', models.CharField(max_length=30, verbose_name='Интересная тема')),
                ('comment', models.TextField(max_length=500, verbose_name='Комментарий')),
                ('created', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created'],
            },
        ),
    ]
