# Generated by Django 6.0 on 2025-12-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='topic',
            field=models.CharField(choices=[('Живопись', 'Живопись'), ('Иллюстрация', 'Иллюстрация'), ('Цифровое искусство', 'Цифровое искусство'), ('Ручная работа', 'Ручная работа'), ('Другое', 'Другое')], default='Живопись', max_length=30, verbose_name='Интересная тема'),
        ),
    ]
